
name: Generate Automata Diagrams


on:
  push:
    paths:
      - 'exercises/**.dot'


jobs:
  generate-svg:

    runs-on: ubuntu-latest


    permissions:
      contents: write


    steps:

      - name: Check out the repository
        uses: actions/checkout@v3
        with:

          fetch-depth: 2


      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz


      - name: Generate SVG files from DOT
        run: |
          find exercises -type f -name "*.dot" | while read dotfile; do
            svgfile="${dotfile%.dot}.svg"
            echo "Generating $svgfile from $dotfile"
            dot -Tsvg "$dotfile" -o "$svgfile"
          done


      - name: Get Exercise Name
        id: get_name
        run: |
          # Este comando busca el primer archivo .dot modificado en el último commit,
          # extrae el nombre de su carpeta y lo guarda en una variable de entorno.
          echo "EXERCISE_NAME=$(basename $(dirname $(git diff --name-only HEAD~1 HEAD | grep '\.dot$' | head -n 1)))" >> $GITHUB_ENV


      - name: Commit and push generated SVG files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:

          commit_message: 'chore: Auto-generate SVG diagrams [${{ env.EXERCISE_NAME }}]'
          file_pattern: "exercises/**/*.svg"